codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
      backend:
        target: 85%
        flags:
          - backend
      frontend:
        target: 75%
        flags:
          - frontend

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

flags:
  backend:
    paths:
      - customer-persona-api/
  frontend:
    paths:
      - customer-persona-app/